server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://10.211.55.4:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/member/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl